name: Go

on:
  push:
    # commits only, not tags
    branches:
      - '**'

permissions:
  contents: read

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  update-latest-release-tag:
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Run latest-tag
        uses: EndBug/latest-tag@7589411ebda7bc8f98deb2dbc37e3dc45828f7d0 # v1.6.2

  release:
    name: Build and publish release
    needs: update-latest-release-tag
    runs-on: ubuntu-latest
    permissions:
      contents: write  # delete and upload assets
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v4
    - name: Delete old release assets
      uses: mknejp/delete-release-assets@a1a36d1b6c6ddd9226a08e9978a5b4b973d48c0d
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        assets: |
          tofail-*-${{ matrix.goos }}-${{ matrix.goarch }}-*.tar.gz*
          tofail-*-${{ matrix.goos }}-${{ matrix.goarch }}-*.zip*
        fail-if-no-assets: false
        fail-if-no-release: false
    - run: echo "ASSET_TIMESTMP=$(date -u +%Y%m%d)" >> ${GITHUB_ENV}
    - run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}
    - uses: wangyoucao577/go-release-action@6ac7dba1f9e61850053324549cb6bc88e4b473d2 # 1.51
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: '1.18'
        release_tag: latest
        overwrite: true
        extra_files: LICENSE README.md
        asset_name: "tofail-${{ env.ASSET_TIMESTMP }}-${{ env.SHA_SHORT }}-${{ matrix.goos }}-${{ matrix.goarch }}"
