name: Go

on:
  push:
    # commits only, not tags
    branches:
      - '**'

permissions:
  contents: read

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  update-latest-release-tag:
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Run latest-tag
        uses: EndBug/latest-tag@7589411ebda7bc8f98deb2dbc37e3dc45828f7d0 # v1.6.2
