on:
  push:
    tags:
      - 'latest'

permissions:
  contents: read

jobs:
  release:
    name: Build and publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # for go-release-action to upload assets
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@6ac7dba1f9e61850053324549cb6bc88e4b473d2 # 1.51
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: '1.18'
        release_tag: ${{ github.ref }}
        overwrite: true
        extra_files: LICENSE README.md
        asset_name: "tofail-${{ env.BUILD_TIME }}-${{ matrix.goos }}-${{ matrix.goarch }}"
